name: build

on:
  push:
    branches:
      - aarch64_org.umccr.java_package
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  build:
    environment: ${{ inputs.environment }}
    runs-on: [ubuntu-24.04-arm]
    steps:
      - name: Install gpg secret key
        run: |
          echo -n "$ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY" | base64 --decode | gpg --import
          # Verify gpg secret key
          gpg --list-secret-keys --keyid-format LONG

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gradle

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'corretto'
          server-id: central
          server-username: umccr
          server-password: $CENTRAL_WEB_PASSWORD
          gpg-private-key: $ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY
          gpg-passphrase: $ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish package
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          MAVEN_USERNAME: $CENTRAL_TOKEN_USERNAME
          MAVEN_PASSWORD: $CENTRAL_TOKEN_PASSWORD
          ORG_GRADLE_PROJECT_mavenCentralUsername: $ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME
          ORG_GRADLE_PROJECT_mavenCentralPassword: $ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD
          ORG_GRADLE_PROJECT_signingInMemoryKey: $ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: $ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: $ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD
