name: build
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - multiplatform_libbwa_blobs
  workflow_run:
    workflows: ["Generate libbwa blobs"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  build:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gradle

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Download Release Assets
        uses: actions/download-release-asset@v1
        with:
          owner: umccr
          repo: gatk-bwamem-jni
          tag: ${{ github.event.workflow_run.head_commit.id }}
          asset_name: '*.so,*.dylib'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy Artifacts to Resources
        run: |
          cp *.so *.dylib ./build/resources/main/
          find ./build

#      - name: Publish package
#        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
#        env:
#          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
#          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
#          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
#          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID }}
#          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
