name: build

on:
  push:
    branches:
      - aarch64_org.umccr.java_package

jobs:
  build:
    runs-on: [ubuntu-24.04-arm]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'corretto'
          server-id: central
          server-username: umccr
          server-password: ${{ secrets.MAVEN_PASSWORD }}
          #gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          #gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Set version
        run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}
      - name: Publish package
        run: mvn -P release --batch-mode deploy -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          #MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
